#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            2
bspc config normal_border_color   \#676e95
bspc config focused_border_color  \#60adec

bspc config split_ratio           0.5
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc rule -a \* node="@/2" splite_dir="south"
bspc rule -a Lxappearance         state=floating
bspc rule -a Nitrogen             state=floating
bspc rule -a Pavucontrol          state=floating
bspc rule -a vlc                  state=floating center=true \
                                  rectangle=1280x720+0+0

$HOME/.config/tetrago/autostart.sh &
$HOME/.config/polybar/start.sh &
